spring.application.name=EventTracker
spring.profiles.active=dev

# Upload settings
app.upload.dir=uploads
app.upload.max-size=5242880
app.upload.allowed-types=image/jpeg,image/png,image/webp

# Admin user (created on first startup if no admin exists)
app.admin.name=Admin
app.admin.email=admin@eventtracker.com
app.admin.password=admin123
