server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirige las peticiones de ruta /tracker/api al backend
    location /tracker/api/ {
        # host.docker.internal permite acceder al localhost de tu máquina desde el contenedor
        proxy_pass http://host.docker.internal:7022/tracker/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirige las peticiones de ruta /images al backend
    location /images/ {
        proxy_pass http://host.docker.internal:7022/tracker/api/images/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}